<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MoveUp" Id="{c1094bb1-d2f6-468f-93a8-56ebf9fe4836}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MoveUp EXTENDS GuardMove
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="className" Id="{f3c5538d-a1db-414c-b088-3a2b7e12f57c}">
      <Declaration><![CDATA[(*

short summary
=================
This abstract property returns the class name of the concrete object, 
which is useful for logging/debugging purpose or to check the class name
for ``__DELETE`` in factories (sometimes it's necessary to do more 
than just to free the memory).

.. <legal notes>

legal notes
=================
| SPDX-FileCopyrightText: © 2022 ekvip automation GmbH <info@ekvip.de>
| SPDX-License-Identifier: Apache-2.0
| For details check: Apache-2.0_

.. _Apache-2.0: https://www.apache.org/licenses/LICENSE-2.0

.. </legal notes>

*)
PROPERTY className : CNM_AbstractObject.ClassName
]]></Declaration>
      <Get Name="Get" Id="{2be7ccd5-cd9d-4e37-89cd-2c09c8176995}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[className := 'MoveUp';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="direction" Id="{29b1c5db-12e4-4678-90b0-7c8e04f7e1b1}">
      <Declaration><![CDATA[PROPERTY PROTECTED direction : Rotation
]]></Declaration>
      <Get Name="Get" Id="{80006c31-1add-466f-ac89-742d4197a330}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[direction := Rotation.UP;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>